version: "2"
services:

  backend:
    image: "node:latest"
    networks:
      - spotify_app
    ports:
      - "3002:3002"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/home/node/app
    command: /bin/sh -c "npm install ; npm run start"
    depends_on:
      - redis


  frontend:
    image: "node:latest"
    networks:
      - spotify_app
    ports:
      - "3001:3001"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend:/home/node/app
    command: /bin/sh -c "npm install ; npm run start"



  redis:
    image: redis
    networks:
      - spotify_app
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server --requirepass passwd --save 60 1 --loglevel warning



  insights:
    image: redislabs/redisinsight:latest
    user: 1000:1000
    networks:
      - spotify_app
    ports:
      - "8001:8001"
    volumes:
      - ./redisinsight/:/db

networks:
  spotify_app:
    name: spotify_app

